# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		Makefile
#		Purpose :	Make test file
#		Date :		5th November 2024
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

include ../../../build_env/common.make

OBJECT = $(BINDIR)test.prg
SOURCES = ../../common/00setup.inc 20start.asm 
MODULES = common ifloat.test

all: asm65

prelim:


