# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		Makefile
#		Purpose :	Make tables for polynomial module
#		Date :		13th November 2024
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

include ../../build_env/common.make

all: 
	cp $(ROOTDIR)documents/ifloat-reference/coefficients.acme active/_coefficients.asm
	
